# Generated by Django 3.2.8 on 2021-10-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Couese',
            new_name='Courses',
        ),
    ]
